### PR TITLE
Use runAndReturn to get result of function executed inside withId

### PR DESCRIPTION
**Pull request by HEYGUL**

### CODE REVIEW

**Comment by toboid** [comment]
@HEYGUL thanks for this. Would you mind adding for the `bindId` function too so that we can keep some symmetry?

Also we'll need to add tests for this functionality.

**Comment by HEYGUL** [comment]
I can add the same `bindId` function too.
Regarding unit tests, I am not confortable with the tests in place. I can add tests but I would need adding mocha chai.
Let me know if I can do it, otherwise, I would be glad to get help from you .

Edit: I had a look to `ava` and get enough understanding to add Unit Tests.
Please have a look to latest commit ^^

**Review by toboid — APPROVED** [review]

**Comment by toboid** [comment]
published as 3.0.0

**Comment by HEYGUL** [comment]
Hi,
I had a look to v3.0.0 and only CHANGELOG and README seem to have been updated.
index.js and tests did not change.
Any idea why ?

**Comment by toboid** [comment]
Sorry @HEYGUL this was error on my part. Now republished as 3.0.1 and changes are there this time

**Comment by HEYGUL** [comment]
Great! Everything is working fine now! Many thanks for your work.
I wish all the best :-)

**Pull request merged**
